name: Build my custom Framework laptop iso image 

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - run: nix-build ./ -A config.system.build.isoImage -I nixos-config=custom-iso.nix