name: Example workflow using use-nix-action

on: [push]

name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - run: nix-build ./ -A config.system.build.isoImage -I nixos-config=custom-iso.nix