name: Build my custom Framework laptop iso image 

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27

    - run: nix-shell s-generators --run "nixos-generate --format iso --configuration ./custom-iso.nix -o result"