name: Build my custom Framework laptop iso image 

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - run: mkdir -p /build/nixpkgs && \
            cd nixpkgs && \
            git init && \
            git remote add origin https://github.com/NixOS/nixpkgs.git && \
            git fetch --depth 1 origin && \
            git checkout FETCH_HEAD && \
            cd ../

    
    - run: nix-shell -p nixos-generators --run "nixos-generate --format iso --configuration ./custom-iso.nix -o result"